name: task_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  # hive: ^2.0.5
  # hive_flutter: ^1.1.0
  intl: ^0.17.0
  # path_provider: ^2.0.9
  rxdart: ^0.27.2
  sqflite: ^2.0.0+4

dev_dependencies:
  # build_runner: ^2.1.7
  # flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  
dependency_overrides:
  platform: ^3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
