const Map<String, String> ar = {
  "Add Task": "اضف مهمة",
  "Tasks": "المهام",
  "Add Task here":" اضف مهمة هنا",
  "Note":"الملاحظة",
  "Title":"عنوان",
  "Date":"التاريخ",
  "Start Time":"وقت البداية",
  "End Time":"وقت النهاية",
  "Remind":"التذكير",
  "Repeat":"التكرار",
  "Create Task":"انشاء مهمة",
  "Color":"اللون",
  "required":"مطلوب",
  "all field is required!":"جميع الحقول مطلوبة",
  "minutes early":"قبل دقيقة",
  "None":"بدون",
  "Daily":"يومي",
  "Weekly":"اسبوعي",
  "Monthly":"شهري",
  "Delete All Task":"حذف جميع المهام",
  "Do you want to delete all tasks?":"هل تريد حذف جميع المهام؟",
  "delete":"حذف",
  "cancel":"الغاء",
  "Add Tasks":" +  اضافة مهمة ",
  "Task Completed":"اكمال المهمة",
  "Completed":"اكتملت",
  "task has been Completed..":"تم اكمال المهمة..",
  "Delete Task":"حذق المهمة",
  "Delete":"حذف ",
  "task has been deleted..":"تم حذف المهمة..",
  "you dont have any tasks yet":" ليس لديك مهام بعد ",
  "Today":"اليوم",
  "Cancel":"الغاء",
};
