const Map<String, String> en = {
  "Tasks": "Tasks",
  "Add Task": "Add Task",
  "Add Task here":"Add Task here",
  "Note" :"Note",
  "Title":"Title",
  "Date":"Date",
  "Start Time":"Start Time",
  "End Time":"End Time",
  "Remind":"Remind",
  "Repeat":"Repeat",
  "Create Task":"Create Task",
  "Color":"Color",
  "required" :"required",
  "all field is required!":"all field is required!",
  "minutes early":"minutes early",
  "None":"None",
  "Daily":"Daily",
  "Weekly":"Weekly",
  "Monthly":"Monthly",
  "Delete All Task":"Delete All Task",
  "Do you want to delete all tasks?":"Do you want to delete all tasks?",
  "delete":"delete",
  "cancel":"cancel",
  "Add Tasks":" +  Add Tasks ",
  "Task Completed":"Task Completed",
  "Completed":"Completed",
  "task has been Completed..":"task has been Completed..",
  "Delete Task":"Delete Task",
  "Delete":"Delete",
  "task has been deleted..":"task has been deleted..",
  "you dont have any tasks yet":"you dont have any tasks yet",
  "Today":"Today",
  "Cancel":"Cancel",

};
